### PR TITLE
feat: add support for multiple image links

### PR DESCRIPTION
**Pull request by xizhao**

### CODE REVIEW

**Comment by bcoe** [comment]
@xizhao a couple comments on this pull, but looking great \o/

1) mind adding a test for images with links, shouldn't be too hard I bet you can use: https://github.com/npm/annotation-poller/blob/master/test.js#L52 as a model (just note that the fingerprint has to be unique, so you'll switch it from `b` to like `bbb` or something).
2. let's add an additional conditional check to the mustache, so that it only renders the linked image if an href is set.
3. might be worth adding some inline style that removes the border.

**Comment by xizhao** [comment]
Also added functionality for multiple/mixed image links, so you can render (for instance), an icon button toolbar.

**Comment by bcoe** [comment]
@xizhao awesome I'll rebase and land this today \o/

**Comment by bcoe** [comment]
@xizhao rebased this in: https://github.com/npm/annotation-poller/pull/10

**Pull request closed without merging**
